name: Deploy React App
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test Application
        run: npm run test
      - name: Lint Application
        run: npm run lint
      - name: Build Application
        run: npm run build
      - name: Deploy
        run: echo Deploying...
